// 英语启蒙单词库 —— 200词，7周主题，覆盖一二年级新课标
// 生成日期：2026-07-10

var ENGLISH_WORDS = [
  // =====================
  // 第1周：数字颜色（25词）
  // =====================
  { id: 'ew001', en: 'one',   zh: '一',   emoji: '1️⃣', category: 'number',  week: 1 },
  { id: 'ew002', en: 'two',   zh: '二',   emoji: '2️⃣', category: 'number',  week: 1 },
  { id: 'ew003', en: 'three', zh: '三',   emoji: '3️⃣', category: 'number',  week: 1 },
  { id: 'ew004', en: 'four',  zh: '四',   emoji: '4️⃣', category: 'number',  week: 1 },
  { id: 'ew005', en: 'five',  zh: '五',   emoji: '5️⃣', category: 'number',  week: 1 },
  { id: 'ew006', en: 'six',   zh: '六',   emoji: '6️⃣', category: 'number',  week: 1 },
  { id: 'ew007', en: 'seven', zh: '七',   emoji: '7️⃣', category: 'number',  week: 1 },
  { id: 'ew008', en: 'eight', zh: '八',   emoji: '8️⃣', category: 'number',  week: 1 },
  { id: 'ew009', en: 'nine',  zh: '九',   emoji: '9️⃣', category: 'number',  week: 1 },
  { id: 'ew010', en: 'ten',   zh: '十',   emoji: '🔟', category: 'number',  week: 1 },
  { id: 'ew011', en: 'eleven',    zh: '十一',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew012', en: 'twelve',    zh: '十二',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew013', en: 'thirteen',  zh: '十三',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew014', en: 'fourteen',  zh: '十四',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew015', en: 'fifteen',   zh: '十五',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew016', en: 'sixteen',   zh: '十六',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew017', en: 'seventeen', zh: '十七',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew018', en: 'eighteen',  zh: '十八',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew019', en: 'nineteen',  zh: '十九',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew020', en: 'twenty',    zh: '二十',   emoji: '🔢', category: 'number', week: 1 },
  { id: 'ew021', en: 'red',    zh: '红色',   emoji: '🔴', category: 'color', week: 1 },
  { id: 'ew022', en: 'blue',   zh: '蓝色',   emoji: '🔵', category: 'color', week: 1 },
  { id: 'ew023', en: 'green',  zh: '绿色',   emoji: '🟢', category: 'color', week: 1 },
  { id: 'ew024', en: 'yellow', zh: '黄色',   emoji: '🟡', category: 'color', week: 1 },
  { id: 'ew025', en: 'white',  zh: '白色',   emoji: '⚪', category: 'color', week: 1 },

  // =====================
  // 第2周：家庭人物（30词）
  // =====================
  { id: 'ew026', en: 'mother', zh: '妈妈', emoji: '👩', category: 'family', week: 2 },
  { id: 'ew027', en: 'father', zh: '爸爸', emoji: '👨', category: 'family', week: 2 },
  { id: 'ew028', en: 'sister', zh: '姐妹', emoji: '👧', category: 'family', week: 2 },
  { id: 'ew029', en: 'brother',zh: '兄弟', emoji: '👦', category: 'family', week: 2 },
  { id: 'ew030', en: 'grandma',zh: '奶奶/外婆', emoji: '👵', category: 'family', week: 2 },
  { id: 'ew031', en: 'grandpa',zh: '爷爷/外公', emoji: '👴', category: 'family', week: 2 },
  { id: 'ew032', en: 'baby',   zh: '宝宝', emoji: '👶', category: 'family', week: 2 },
  { id: 'ew033', en: 'friend', zh: '朋友', emoji: '🤝', category: 'family', week: 2 },
  { id: 'ew034', en: 'teacher',zh: '老师', emoji: '👩‍🏫', category: 'family', week: 2 },
  { id: 'ew035', en: 'boy',    zh: '男孩', emoji: '👦', category: 'family', week: 2 },
  { id: 'ew036', en: 'girl',   zh: '女孩', emoji: '👧', category: 'family', week: 2 },
  { id: 'ew037', en: 'man',    zh: '男人', emoji: '👨', category: 'family', week: 2 },
  { id: 'ew038', en: 'woman',  zh: '女人', emoji: '👩', category: 'family', week: 2 },
  { id: 'ew039', en: 'child',  zh: '孩子', emoji: '🧒', category: 'family', week: 2 },
  { id: 'ew040', en: 'people', zh: '人们', emoji: '👥', category: 'family', week: 2 },
  { id: 'ew041', en: 'classmate', zh: '同学', emoji: '👫', category: 'family', week: 2 },
  { id: 'ew042', en: 'uncle',  zh: '叔叔/舅舅', emoji: '👨', category: 'family', week: 2 },
  { id: 'ew043', en: 'aunt',   zh: '阿姨/姑姑', emoji: '👩', category: 'family', week: 2 },
  { id: 'ew044', en: 'son',    zh: '儿子', emoji: '👦', category: 'family', week: 2 },
  { id: 'ew045', en: 'daughter',zh: '女儿', emoji: '👧', category: 'family', week: 2 },
  { id: 'ew046', en: 'parent', zh: '父母', emoji: '👪', category: 'family', week: 2 },
  { id: 'ew047', en: 'family', zh: '家庭', emoji: '👨‍👩‍👧‍👦', category: 'family', week: 2 },
  { id: 'ew048', en: 'name',   zh: '名字', emoji: '📛', category: 'family', week: 2 },
  { id: 'ew049', en: 'he',     zh: '他',   emoji: '🙋‍♂️', category: 'family', week: 2 },
  { id: 'ew050', en: 'she',    zh: '她',   emoji: '🙋‍♀️', category: 'family', week: 2 },
  { id: 'ew051', en: 'I',      zh: '我',   emoji: '🙋',   category: 'family', week: 2 },
  { id: 'ew052', en: 'you',    zh: '你',   emoji: '👉',   category: 'family', week: 2 },
  { id: 'ew053', en: 'we',     zh: '我们', emoji: '👫',   category: 'family', week: 2 },
  { id: 'ew054', en: 'they',   zh: '他们/她们', emoji: '👥', category: 'family', week: 2 },
  { id: 'ew055', en: 'it',     zh: '它',   emoji: '👉',   category: 'family', week: 2 },

  // =====================
  // 第3周：动物自然（30词）
  // =====================
  { id: 'ew056', en: 'dog',     zh: '狗',   emoji: '🐶', category: 'animal', week: 3 },
  { id: 'ew057', en: 'cat',     zh: '猫',   emoji: '🐱', category: 'animal', week: 3 },
  { id: 'ew058', en: 'bird',    zh: '鸟',   emoji: '🐦', category: 'animal', week: 3 },
  { id: 'ew059', en: 'fish',    zh: '鱼',   emoji: '🐟', category: 'animal', week: 3 },
  { id: 'ew060', en: 'duck',    zh: '鸭子', emoji: '🦆', category: 'animal', week: 3 },
  { id: 'ew061', en: 'pig',     zh: '猪',   emoji: '🐷', category: 'animal', week: 3 },
  { id: 'ew062', en: 'cow',     zh: '奶牛', emoji: '🐮', category: 'animal', week: 3 },
  { id: 'ew063', en: 'tiger',   zh: '老虎', emoji: '🐯', category: 'animal', week: 3 },
  { id: 'ew064', en: 'panda',   zh: '熊猫', emoji: '🐼', category: 'animal', week: 3 },
  { id: 'ew065', en: 'monkey',  zh: '猴子', emoji: '🐵', category: 'animal', week: 3 },
  { id: 'ew066', en: 'rabbit',  zh: '兔子', emoji: '🐰', category: 'animal', week: 3 },
  { id: 'ew067', en: 'elephant',zh: '大象', emoji: '🐘', category: 'animal', week: 3 },
  { id: 'ew068', en: 'lion',    zh: '狮子', emoji: '🦁', category: 'animal', week: 3 },
  { id: 'ew069', en: 'snake',   zh: '蛇',   emoji: '🐍', category: 'animal', week: 3 },
  { id: 'ew070', en: 'bear',    zh: '熊',   emoji: '🐻', category: 'animal', week: 3 },
  { id: 'ew071', en: 'horse',   zh: '马',   emoji: '🐴', category: 'animal', week: 3 },
  { id: 'ew072', en: 'sheep',   zh: '绵羊', emoji: '🐑', category: 'animal', week: 3 },
  { id: 'ew073', en: 'chicken', zh: '鸡',   emoji: '🐔', category: 'animal', week: 3 },
  { id: 'ew074', en: 'frog',    zh: '青蛙', emoji: '🐸', category: 'animal', week: 3 },
  { id: 'ew075', en: 'mouse',   zh: '老鼠', emoji: '🐭', category: 'animal', week: 3 },
  { id: 'ew076', en: 'ant',     zh: '蚂蚁', emoji: '🐜', category: 'animal', week: 3 },
  { id: 'ew077', en: 'bee',     zh: '蜜蜂', emoji: '🐝', category: 'animal', week: 3 },
  { id: 'ew078', en: 'sun',     zh: '太阳', emoji: '☀️',  category: 'nature', week: 3 },
  { id: 'ew079', en: 'moon',    zh: '月亮', emoji: '🌙', category: 'nature', week: 3 },
  { id: 'ew080', en: 'star',    zh: '星星', emoji: '⭐',  category: 'nature', week: 3 },
  { id: 'ew081', en: 'tree',    zh: '树',   emoji: '🌳', category: 'nature', week: 3 },
  { id: 'ew082', en: 'flower',  zh: '花',   emoji: '🌸', category: 'nature', week: 3 },
  { id: 'ew083', en: 'grass',   zh: '草',   emoji: '🌿', category: 'nature', week: 3 },
  { id: 'ew084', en: 'rain',    zh: '雨',   emoji: '🌧️',  category: 'nature', week: 3 },
  { id: 'ew085', en: 'snow',    zh: '雪',   emoji: '❄️',  category: 'nature', week: 3 },

  // =====================
  // 第4周：食物饮品（30词）
  // =====================
  { id: 'ew086', en: 'apple',      zh: '苹果',   emoji: '🍎', category: 'food', week: 4 },
  { id: 'ew087', en: 'banana',     zh: '香蕉',   emoji: '🍌', category: 'food', week: 4 },
  { id: 'ew088', en: 'orange',     zh: '橙子',   emoji: '🍊', category: 'food', week: 4 },
  { id: 'ew089', en: 'grape',      zh: '葡萄',   emoji: '🍇', category: 'food', week: 4 },
  { id: 'ew090', en: 'pear',       zh: '梨',     emoji: '🍐', category: 'food', week: 4 },
  { id: 'ew091', en: 'watermelon', zh: '西瓜',   emoji: '🍉', category: 'food', week: 4 },
  { id: 'ew092', en: 'egg',        zh: '鸡蛋',   emoji: '🥚', category: 'food', week: 4 },
  { id: 'ew093', en: 'milk',       zh: '牛奶',   emoji: '🥛', category: 'food', week: 4 },
  { id: 'ew094', en: 'bread',      zh: '面包',   emoji: '🍞', category: 'food', week: 4 },
  { id: 'ew095', en: 'cake',       zh: '蛋糕',   emoji: '🎂', category: 'food', week: 4 },
  { id: 'ew096', en: 'rice',       zh: '米饭',   emoji: '🍚', category: 'food', week: 4 },
  { id: 'ew097', en: 'noodle',     zh: '面条',   emoji: '🍜', category: 'food', week: 4 },
  { id: 'ew098', en: 'water',      zh: '水',     emoji: '💧', category: 'food', week: 4 },
  { id: 'ew099', en: 'juice',      zh: '果汁',   emoji: '🧃', category: 'food', week: 4 },
  { id: 'ew100', en: 'tea',        zh: '茶',     emoji: '🍵', category: 'food', week: 4 },
  { id: 'ew101', en: 'meat',       zh: '肉',     emoji: '🥩', category: 'food', week: 4 },
  { id: 'ew102', en: 'fish',       zh: '鱼肉',   emoji: '🐟', category: 'food', week: 4 },
  { id: 'ew103', en: 'chicken',    zh: '鸡肉',   emoji: '🍗', category: 'food', week: 4 },
  { id: 'ew104', en: 'ice-cream',  zh: '冰淇淋', emoji: '🍦', category: 'food', week: 4 },
  { id: 'ew105', en: 'candy',      zh: '糖果',   emoji: '🍬', category: 'food', week: 4 },
  { id: 'ew106', en: 'cookie',     zh: '饼干',   emoji: '🍪', category: 'food', week: 4 },
  { id: 'ew107', en: 'hamburger',  zh: '汉堡',   emoji: '🍔', category: 'food', week: 4 },
  { id: 'ew108', en: 'pizza',      zh: '披萨',   emoji: '🍕', category: 'food', week: 4 },
  { id: 'ew109', en: 'hot',    zh: '热的',   emoji: '🔥', category: 'food', week: 4 },
  { id: 'ew110', en: 'eat',    zh: '吃',     emoji: '🍽️',  category: 'food', week: 4 },
  { id: 'ew111', en: 'drink',  zh: '喝',     emoji: '🥤', category: 'food', week: 4 },
  { id: 'ew112', en: 'hungry', zh: '饿的',   emoji: '😋', category: 'food', week: 4 },
  { id: 'ew113', en: 'thirsty',zh: '渴的',   emoji: '🥵', category: 'food', week: 4 },
  { id: 'ew114', en: 'yummy',  zh: '好吃的', emoji: '😋', category: 'food', week: 4 },
  { id: 'ew115', en: 'dog',    zh: '热狗',   emoji: '🌭', category: 'food', week: 4 },

  // =====================
  // 第5周：学校文具（30词）
  // =====================
  { id: 'ew116', en: 'book',       zh: '书',     emoji: '📖', category: 'school', week: 5 },
  { id: 'ew117', en: 'pen',        zh: '钢笔',   emoji: '🖊️',  category: 'school', week: 5 },
  { id: 'ew118', en: 'pencil',     zh: '铅笔',   emoji: '✏️',  category: 'school', week: 5 },
  { id: 'ew119', en: 'ruler',      zh: '尺子',   emoji: '📏', category: 'school', week: 5 },
  { id: 'ew120', en: 'eraser',     zh: '橡皮',   emoji: '🧹', category: 'school', week: 5 },
  { id: 'ew121', en: 'bag',        zh: '书包',   emoji: '🎒', category: 'school', week: 5 },
  { id: 'ew122', en: 'desk',       zh: '书桌',   emoji: '🪑', category: 'school', week: 5 },
  { id: 'ew123', en: 'chair',      zh: '椅子',   emoji: '🪑', category: 'school', week: 5 },
  { id: 'ew124', en: 'blackboard', zh: '黑板',   emoji: '⬛', category: 'school', week: 5 },
  { id: 'ew125', en: 'school',     zh: '学校',   emoji: '🏫', category: 'school', week: 5 },
  { id: 'ew126', en: 'classroom',  zh: '教室',   emoji: '🏫', category: 'school', week: 5 },
  { id: 'ew127', en: 'paper',      zh: '纸',     emoji: '📄', category: 'school', week: 5 },
  { id: 'ew128', en: 'crayon',     zh: '蜡笔',   emoji: '🖍️',  category: 'school', week: 5 },
  { id: 'ew129', en: 'glue',       zh: '胶水',   emoji: '🧴', category: 'school', week: 5 },
  { id: 'ew130', en: 'scissors',   zh: '剪刀',   emoji: '✂️',  category: 'school', week: 5 },
  { id: 'ew131', en: 'notebook',   zh: '笔记本', emoji: '📓', category: 'school', week: 5 },
  { id: 'ew132', en: 'homework',   zh: '作业',   emoji: '📝', category: 'school', week: 5 },
  { id: 'ew133', en: 'teacher',    zh: '老师',   emoji: '👩‍🏫', category: 'school', week: 5 },
  { id: 'ew134', en: 'student',    zh: '学生',   emoji: '👩‍🎓', category: 'school', week: 5 },
  { id: 'ew135', en: 'read',       zh: '阅读',   emoji: '📖', category: 'school', week: 5 },
  { id: 'ew136', en: 'write',      zh: '写字',   emoji: '✍️',  category: 'school', week: 5 },
  { id: 'ew137', en: 'draw',       zh: '画画',   emoji: '🎨', category: 'school', week: 5 },
  { id: 'ew138', en: 'learn',      zh: '学习',   emoji: '📚', category: 'school', week: 5 },
  { id: 'ew139', en: 'sing',       zh: '唱歌',   emoji: '🎤', category: 'school', week: 5 },
  { id: 'ew140', en: 'dance',      zh: '跳舞',   emoji: '💃', category: 'school', week: 5 },
  { id: 'ew141', en: 'play',       zh: '玩',     emoji: '🎮', category: 'school', week: 5 },
  { id: 'ew142', en: 'Chinese',    zh: '语文',   emoji: '🀄', category: 'school', week: 5 },
  { id: 'ew143', en: 'English',    zh: '英语',   emoji: '🇬🇧', category: 'school', week: 5 },
  { id: 'ew144', en: 'math',       zh: '数学',   emoji: '🔢', category: 'school', week: 5 },
  { id: 'ew145', en: 'music',      zh: '音乐',   emoji: '🎵', category: 'school', week: 5 },

  // =====================
  // 第6周：身体动作（30词）
  // =====================
  { id: 'ew146', en: 'head',  zh: '头',   emoji: '🗣️',  category: 'body', week: 6 },
  { id: 'ew147', en: 'eye',   zh: '眼睛', emoji: '👁️',  category: 'body', week: 6 },
  { id: 'ew148', en: 'ear',   zh: '耳朵', emoji: '👂',  category: 'body', week: 6 },
  { id: 'ew149', en: 'nose',  zh: '鼻子', emoji: '👃',  category: 'body', week: 6 },
  { id: 'ew150', en: 'mouth', zh: '嘴巴', emoji: '👄',  category: 'body', week: 6 },
  { id: 'ew151', en: 'face',  zh: '脸',   emoji: '😊',  category: 'body', week: 6 },
  { id: 'ew152', en: 'hand',  zh: '手',   emoji: '✋',   category: 'body', week: 6 },
  { id: 'ew153', en: 'foot',  zh: '脚',   emoji: '🦶',  category: 'body', week: 6 },
  { id: 'ew154', en: 'arm',   zh: '手臂', emoji: '💪',  category: 'body', week: 6 },
  { id: 'ew155', en: 'leg',   zh: '腿',   emoji: '🦵',  category: 'body', week: 6 },
  { id: 'ew156', en: 'hair',  zh: '头发', emoji: '💇',  category: 'body', week: 6 },
  { id: 'ew157', en: 'tooth', zh: '牙齿', emoji: '🦷',  category: 'body', week: 6 },
  { id: 'ew158', en: 'body',  zh: '身体', emoji: '🧍',  category: 'body', week: 6 },
  { id: 'ew159', en: 'run',   zh: '跑',   emoji: '🏃',  category: 'action', week: 6 },
  { id: 'ew160', en: 'jump',  zh: '跳',   emoji: '🦘',  category: 'action', week: 6 },
  { id: 'ew161', en: 'walk',  zh: '走',   emoji: '🚶',  category: 'action', week: 6 },
  { id: 'ew162', en: 'swim',  zh: '游泳', emoji: '🏊',  category: 'action', week: 6 },
  { id: 'ew163', en: 'fly',   zh: '飞',   emoji: '🕊️',  category: 'action', week: 6 },
  { id: 'ew164', en: 'sit',   zh: '坐',   emoji: '🧘',  category: 'action', week: 6 },
  { id: 'ew165', en: 'stand', zh: '站',   emoji: '🧍',  category: 'action', week: 6 },
  { id: 'ew166', en: 'eat',   zh: '吃',   emoji: '🍽️',  category: 'action', week: 6 },
  { id: 'ew167', en: 'drink', zh: '喝',   emoji: '🥤',  category: 'action', week: 6 },
  { id: 'ew168', en: 'see',   zh: '看见', emoji: '👀',  category: 'action', week: 6 },
  { id: 'ew169', en: 'hear',  zh: '听见', emoji: '👂',  category: 'action', week: 6 },
  { id: 'ew170', en: 'touch', zh: '触摸', emoji: '🤚',  category: 'action', week: 6 },
  { id: 'ew171', en: 'smell', zh: '闻',   emoji: '👃',  category: 'action', week: 6 },
  { id: 'ew172', en: 'sleep', zh: '睡觉', emoji: '😴',  category: 'action', week: 6 },
  { id: 'ew173', en: 'wake',  zh: '醒来', emoji: '⏰',  category: 'action', week: 6 },
  { id: 'ew174', en: 'open',  zh: '打开', emoji: '📂',  category: 'action', week: 6 },
  { id: 'ew175', en: 'close', zh: '关闭', emoji: '🔒',  category: 'action', week: 6 },

  // =====================
  // 第7周：形容词综合（25词）
  // =====================
  { id: 'ew176', en: 'big',        zh: '大的',   emoji: '🐘', category: 'adj', week: 7 },
  { id: 'ew177', en: 'small',      zh: '小的',   emoji: '🐭', category: 'adj', week: 7 },
  { id: 'ew178', en: 'long',       zh: '长的',   emoji: '🐍', category: 'adj', week: 7 },
  { id: 'ew179', en: 'short',      zh: '短的',   emoji: '📏', category: 'adj', week: 7 },
  { id: 'ew180', en: 'tall',       zh: '高的',   emoji: '🦒', category: 'adj', week: 7 },
  { id: 'ew181', en: 'new',        zh: '新的',   emoji: '✨', category: 'adj', week: 7 },
  { id: 'ew182', en: 'old',        zh: '旧的/老的', emoji: '👴', category: 'adj', week: 7 },
  { id: 'ew183', en: 'good',       zh: '好的',   emoji: '👍', category: 'adj', week: 7 },
  { id: 'ew184', en: 'bad',        zh: '坏的',   emoji: '👎', category: 'adj', week: 7 },
  { id: 'ew185', en: 'happy',      zh: '快乐的', emoji: '😊', category: 'adj', week: 7 },
  { id: 'ew186', en: 'sad',        zh: '伤心的', emoji: '😢', category: 'adj', week: 7 },
  { id: 'ew187', en: 'hot',        zh: '热的',   emoji: '🔥', category: 'adj', week: 7 },
  { id: 'ew188', en: 'cold',       zh: '冷的',   emoji: '❄️',  category: 'adj', week: 7 },
  { id: 'ew189', en: 'nice',       zh: '好的/友善的', emoji: '😊', category: 'adj', week: 7 },
  { id: 'ew190', en: 'beautiful',  zh: '美丽的', emoji: '🌹', category: 'adj', week: 7 },
  { id: 'ew191', en: 'ugly',       zh: '丑陋的', emoji: '💀', category: 'adj', week: 7 },
  { id: 'ew192', en: 'fast',       zh: '快的',   emoji: '🚀', category: 'adj', week: 7 },
  { id: 'ew193', en: 'slow',       zh: '慢的',   emoji: '🐢', category: 'adj', week: 7 },
  { id: 'ew194', en: 'fat',        zh: '胖的',   emoji: '🐷', category: 'adj', week: 7 },
  { id: 'ew195', en: 'thin',       zh: '瘦的',   emoji: '📏', category: 'adj', week: 7 },
  { id: 'ew196', en: 'clean',      zh: '干净的', emoji: '🧹', category: 'adj', week: 7 },
  { id: 'ew197', en: 'dirty',      zh: '脏的',   emoji: '💩', category: 'adj', week: 7 },
  { id: 'ew198', en: 'young',      zh: '年轻的', emoji: '👶', category: 'adj', week: 7 },
  { id: 'ew199', en: 'pretty',     zh: '漂亮的', emoji: '💖', category: 'adj', week: 7 },
  { id: 'ew200', en: 'cute',       zh: '可爱的', emoji: '🥰', category: 'adj', week: 7 }
];
